### ISSUE TITLE
OSError: Can't read data (inflate() failed)

### ISSUE THREAD

**Issue by gqsmmz** [MrZihan/GridMM#15]
Hello, I have found an issue with the depth.hdv5 data of R2R。

Traceback (most recent call last):
  File "train_reverie_obj.py", line 501, in <module>
11111 VLzqgDo317F_82144a4d6cad4c2592b95a570aa89daa
    main(args)
  File "train_reverie_obj.py", line 234, in main
    for step, (name, batch) in enumerate(meta_loader):  
  File "/mnt/storage/home/lss/GridMM/pretrain_src/data/loader.py", line 100, in __iter__
    self.preload(loader_it)
  File "/mnt/storage/home/lss/GridMM/pretrain_src/data/loader.py", line 111, in preload
    self.batch = next(it)
  File "/mnt/storage/home/lss/GridMM/pretrain_src/data/loader.py", line 64, in __iter__
    batch = next(iter_)
  File "/mnt/storage/home/lss/anaconda3/envs/GridMM/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/mnt/storage/home/lss/anaconda3/envs/GridMM/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/mnt/storage/home/lss/anaconda3/envs/GridMM/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/mnt/storage/home/lss/anaconda3/envs/GridMM/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/mnt/storage/home/lss/anaconda3/envs/GridMM/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/storage/home/lss/anaconda3/envs/GridMM/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/storage/home/lss/anaconda3/envs/GridMM/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/storage/home/lss/GridMM/pretrain_src/data/tasks.py", line 390, in __getitem__
    inputs = self.nav_db.get_input(idx+1, 'pos', return_obj_label=True)
  File "/mnt/storage/home/lss/GridMM/pretrain_src/data/dataset.py", line 261, in get_input
    last_vp_angles, last_vp_objids, grid_fts,grid_map,gridmap_pos_fts, target_patch_id = self.get_traj_pano_fts(scan, gt_path)
  File "/mnt/storage/home/lss/GridMM/pretrain_src/data/dataset.py", line 506, in get_traj_pano_fts
    self.global_semantic,self.global_position_x,self.global_position_y,self.global_mask,self.global_map,self.max_x,self.min_x,self.max_y,self.min_y,gridmap_pos_fts, target_patch_id = self.getGlobalMap(scan, vp)
  File "/mnt/storage/home/lss/GridMM/pretrain_src/data/dataset.py", line 360, in getGlobalMap
    depth = self.DepthDB.get_image_feature(scan_id,viewpoint_id)
  File "/mnt/storage/home/lss/GridMM/pretrain_src/data/dataset.py", line 68, in get_image_feature
    ft = self._feature_store[key][...][:].astype(np.uint16)#16整数类型已经占存很小了啊
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/mnt/storage/home/lss/anaconda3/envs/GridMM/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 573, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 182, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (inflate() failed)
Excuse me, is there an error in the file you uploaded

**Comment by gqsmmz** [comment]
The wrong file is the depth.hdf5 in R2R/features

**Comment by MrZihan** [comment]
The file "depth.hdf5" and the code should be fine, as many users have reported that the code runs normally on their machines. The error "Python: h5py OSError: Can't read data (inflate() failed)" is usually caused by a corrupted HDF5 file, such as an incomplete download or an incomplete file copy. I recommend checking the "depth.hdf5" file or considering re-downloading it. Best regards.

**Comment by MrZihan** [comment]
Are you running the code in a Docker container? If so, you can try changing the `--shm-size` setting of the Docker container to ensure that the working processes have enough cache space. 
This [issue#9](https://github.com/MrZihan/GridMM/issues/9) has been solved by this.

**Comment by gqsmmz** [comment]
> Are you running the code in a Docker container? If so, you can try changing the `--shm-size` setting of the Docker container to ensure that the working processes have enough cache space. This [issue#9](https://github.com/MrZihan/GridMM/issues/9) has been solved by this.

Thanks very much! I have solved the problem. Can both pre training and fine-tuning use more gpus to accelerate training without reducing performance, such as using 6 gpus?

![image](https://github.com/user-attachments/assets/fd37a580-bd57-4b84-9f12-666b4b087e20)

**Comment by gqsmmz** [comment]
If the number of gpus increases, how should the batch size be adjusted (for example, the batch size of R2R when using 3 gpus used to be 32, do we need to change it now?). And are there any other parameters that need to be adjusted？

**Comment by MrZihan** [comment]
The batch size in our code corresponds to the number of samples used per GPU, not the total number of samples for all GPUs in a batch.
In some way, in our experience, a larger batch size may result in better performance. But if you want a faster training speed, you can also try to reduce it, because a large batch size also brings a huge IO cost.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: gqsmmz ***@***.***>
Sent: Friday, October 11, 2024 9:14:34 PM
To: MrZihan/GridMM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MrZihan/GridMM] OSError: Can't read data (inflate() failed) (Issue #15)


Hello, I have found an issue with the depth.hdv5 data of R2R。

Original Traceback (most recent call last):
File "/mnt/storage/home/lss/anaconda3/envs/GridMM/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
data = fetcher.fetch(index)
File "/mnt/storage/home/lss/anaconda3/envs/GridMM/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/mnt/storage/home/lss/anaconda3/envs/GridMM/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/mnt/storage/home/lss/GridMM/pretrain_src/data/tasks.py", line 186, in getitem
inputs = self.nav_db.get_input(idx, end_vp_type, return_img_probs=True)
File "/mnt/storage/home/lss/GridMM/pretrain_src/data/dataset.py", line 719, in get_input
last_vp_angles,grid_fts,grid_map,gridmap_pos_fts, target_patch_id = self.get_traj_pano_fts(scan, gt_path)
File "/mnt/storage/home/lss/GridMM/pretrain_src/data/dataset.py", line 795, in get_traj_pano_fts
self.global_semantic,self.global_position_x,self.global_position_y,self.global_mask,self.global_map,self.max_x,self.min_x,self.max_y,self.min_y,gridmap_pos_fts, target_patch_id = self.getGlobalMap(scan, vp)
File "/mnt/storage/home/lss/GridMM/pretrain_src/data/dataset.py", line 359, in getGlobalMap
depth = self.DepthDB.get_image_feature(scan_id,viewpoint_id)
File "/mnt/storage/home/lss/GridMM/pretrain_src/data/dataset.py", line 67, in get_image_feature
ft = self._feature_store[key][...][:].astype(np.uint16)
File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
File "/mnt/storage/home/lss/anaconda3/envs/GridMM/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 573, in getitem
self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
File "h5py/h5d.pyx", line 182, in h5py.h5d.DatasetID.read
File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (inflate() failed)

Excuse me, is there an error in the file you uploaded

―

**Comment by gqsmmz** [comment]
Thank you very much for your patience and timely response! May I ask how to reproduce the 3D visualization result on the right side of the image that you have shown？

![image](https://github.com/user-attachments/assets/4d9e5fea-285c-4cba-b192-a160d1b28210)

**Comment by MrZihan** [comment]
Please refer to the code shown in the picture.
![屏幕截图 2024-10-13 131810](https://github.com/user-attachments/assets/a67eea78-2c05-4507-9f9d-1b49a2c3f138)

**Comment by gqsmmz** [comment]
Thanks! I will check it right away! May I ask where the problem occurred during the testing of VLN-CE?

The config file in the error message has been output in the image

![image](https://github.com/user-attachments/assets/b9482fe3-4353-4d2a-b555-6274b9573414)

**Comment by MrZihan** [comment]
It seems that the dataset files are missing or not located in the specified directory. You can check it.
As you know, since the CVPR deadline is approaching, it's difficult for us to address all small issues one by one. Sincerely apologize.
Best of luck to you.

**Comment by SheldonWongww** [comment]
> > Are you running the code in a Docker container? If so, you can try changing the `--shm-size` setting of the Docker container to ensure that the working processes have enough cache space. This [issue#9](https://github.com/MrZihan/GridMM/issues/9) has been solved by this.
> 
> Thanks very much! I have solved the problem. Can both pre training and fine-tuning use more gpus to accelerate training without reducing performance, such as using 6 gpus?
> 
> ![image](https://github.com/user-attachments/assets/fd37a580-bd57-4b84-9f12-666b4b087e20)

Hello，Could you please tell me how you build your Docker containers?

**Comment by MrZihan** [comment]
> > > Are you running the code in a Docker container? If so, you can try changing the `--shm-size` setting of the Docker container to ensure that the working processes have enough cache space. This [issue#9](https://github.com/MrZihan/GridMM/issues/9) has been solved by this.
> > 
> > 
> > Thanks very much! I have solved the problem. Can both pre training and fine-tuning use more gpus to accelerate training without reducing performance, such as using 6 gpus?
> > ![image](https://github.com/user-attachments/assets/fd37a580-bd57-4b84-9f12-666b4b087e20)
> 
> Hello，Could you please tell me how you build your Docker containers?

For VLN on the discrete environment, please check `Building using Docker` Section in https://github.com/peteanderson80/Matterport3DSimulator

For VLN-CE, please check https://github.com/YicongHong/Discrete-Continuous-VLN

**Comment by SheldonWongww** [comment]
> > Are you running the code in a Docker container? If so, you can try changing the `--shm-size` setting of the Docker container to ensure that the working processes have enough cache space. This [issue#9](https://github.com/MrZihan/GridMM/issues/9) has been solved by this.
> 
> Thanks very much! I have solved the problem. Can both pre training and fine-tuning use more gpus to accelerate training without reducing performance, such as using 6 gpus?
> 
> ![image](https://github.com/user-attachments/assets/fd37a580-bd57-4b84-9f12-666b4b087e20)

hello，could you tell me how you solved this problem？
